---

- hosts: all
  become: true
  tasks:
    - name: Add APT key for google-chrome
      apt_key:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add repository for google-chrome
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present
        filename: google-chrome
        
    - include_tasks: update_cache.yml

    - name: Install google-chrome
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "latest", name: "google-chrome-stable" }
