---

- hosts: all
  become: true
  tasks:
    - name: apt upgrade
      apt:
        upgrade: yes
    - name: autoremove
      apt:
        autoremove: yes
    - name: autoclean
      apt:
        purge: yes
    - name: dist upgrade
      apt:
        upgrade: dist

     