---

- hosts: all
  become: true
  tasks:
    - name: Add APT key for virtual-box-6.0
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present

    - name: Add repository for virtual box
      apt_repository:
        repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{release}} contrib
        state: present
        filename: vbox
        
    - include_tasks: update_cache.yml

    - name: Install virtual-box-6.0 and Vagrant
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "latest", name: "virtualbox-6.0" }
        - { state: "latest", name: "vagrant" }
