---

- hosts: all
  become: true
  tasks:
    - name: Add APT key for visual-code
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add repository for visual-code
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main

        state: present
        filename: vscode
        
    - include_tasks: update_cache.yml

    - name: Install visual-code
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "latest", name: "code" }
